// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AppIcon: typeof import('./components/common/AppIcon.vue')['default']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    BreadCrumb: typeof import('./components/Layout/BreadCrumb.vue')['default']
    EntryItem: typeof import('./components/EntryItem.vue')['default']
    ExchangeCheif: typeof import('./components/ExchangeCheif.vue')['default']
    ExchangeCheifSuit: typeof import('./components/ExchangeCheifSuit.vue')['default']
    ExchangeGolden: typeof import('./components/ExchangeGolden.vue')['default']
    ExchangeResult: typeof import('./components/ExchangeResult.vue')['default']
    ExchangeSuit: typeof import('./components/ExchangeSuit.vue')['default']
    LazyImg: typeof import('./components/common/LazyImg.vue')['default']
    LevelCom: typeof import('./components/LevelCom.vue')['default']
    ShotSuit: typeof import('./components/store/ShotSuit.vue')['default']
    ShotYuhun: typeof import('./components/store/ShotYuhun.vue')['default']
    TheFooter: typeof import('./components/Layout/TheFooter.vue')['default']
    TheHeaderRight: typeof import('./components/Layout/TheHeaderRight.vue')['default']
    TheMenu: typeof import('./components/Layout/TheMenu.vue')['default']
    YuhunDetail: typeof import('./components/store/YuhunDetail.vue')['default']
    YuhunItem: typeof import('./components/YuhunItem.vue')['default']
  }
}

export { }
